# Generated by Django 5.0.4 on 2024-04-23 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0002_relatoriogeral'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatorioGeral',
        ),
    ]
